### PR TITLE
Busmall start

### PR DESCRIPTION
**Pull request by dmarchante**

### CODE REVIEW

**Comment by applena** [comment]
this looks great! I love your styling (as usual).
Love your code comments and the way you populate your object instances. Very clean and sleek. 

 Here are somethings you can work on:

- [x] update user stories to be in the format of "as a developer, I want _______" "as a marketer, I want ________" "as a consumer, I am looking for _________" (-1)
- [x] you are missing your .eslintrc.json (-1)
- [ ] the images are not rendering to the page (its the same filepath issue as you had in salmon cookies) (-1)
- [x] it is best to avoid pop up (alert) boxes if you can. See if you can re-factor your code and remove the event listeners rather than pop up an alert box

**Comment by applena** [comment]
Great updates! The image still aren't showing up in my browser but everything else looks good :)

**Comment by dmarchante** [comment]
Are you looking at it from this branch?

**Comment by applena** [comment]
I was looking at the master

**Pull request merged**
